### ISSUE TITLE
Please tell me how to generate this folder / root/go/bin?

### ISSUE THREAD

**Issue by RecursionHs** [demipoet/demipoet.github.io#1]
Please tell me how to generate this folder / root/go/bin?

**Comment by demipoet** [comment]
Refer to [Section X. Build the node Binary in /root/go/bin Folder](https://github.com/demipoet/demipoet.github.io/blob/main/README.md#x-build-the-node-binary-in-rootgobin-folder) of the Q Guide.

**Comment by RecursionHs** [comment]
When I start it for the first time, I use ps-ef | grep node to show
```
root@vmi1712813:~# ps -ef | grep node
root       17936   17812 99 08:07 pts/2    00:01:34 /tmp/go-build2256667211/b001/exe/node
root       18014   17980  0 08:08 pts/3    00:00:00 grep --color=auto node

```
Didn't see it.
![image](https://github.com/demipoet/demipoet.github.io/assets/36094328/17f906b4-b06e-4583-98fd-58eb3f265a72)

**Comment by RecursionHs** [comment]
When I first started it, use ps 
```
root@vmi1712813:~# ps -ef | grep node
root       17936   17812 99 08:07 pts/2    00:01:34 /tmp/go-build2256667211/b001/exe/node
root       18014   17980  0 08:08 pts/3    00:00:00 grep --color=auto node
```
And my root directory is：
```
root@vmi1712813:~# pwd
/root
root@vmi1712813:~# tree -L 2 go
go
└── pkg
    └── mod

2 directories, 0 files

```

It's not in your file.
![image](https://github.com/demipoet/demipoet.github.io/assets/36094328/d4c53bfa-19c4-4eda-a0e5-7f2613da0b37)

I also looked at my go environment variable
![image](https://github.com/demipoet/demipoet.github.io/assets/36094328/7cf6ed74-ca0b-4169-b4f9-4c906fd2fe8b)
